### ISSUE TITLE
Some of the proxy => forward migrations can result in multiple forward entries in a single server block

### ISSUE THREAD

**Issue by zawachte** [coredns/corefile-migration#71]
I am not sure if the validity of this input or usecase, so maybe it's not even a corner case worth considering, but it looks like if you have an input like:

```
.:53 {
    errors
    health
    loop
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf {
       protocol force_tcp insecure
    }
    proxy . *
    cache 30
    reload
    loadbalance
}
```
migrate would result in:
```
.:53 {
            errors
            health
            loop
            kubernetes cluster.local in-addr.arpa ip6.arpa {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
            }
            prometheus :9153
            forward . /etc/resolv.conf {
                force_tcp
            }
            forward . *
            cache 30
            reload
            loadbalance
            ready
}
```
This could result in coredns pods failing to come up with multiple forward entries in a single server block.

**Comment by chrisohaver** [comment]
Yes. It’s valid case.  I haven’t seen anyone report this before, and it’s been around a long time, so it must not be a very common situation. 

Unfortunately there is no easy/clean/programatic way to replicate multi proxy plugins in coredns using forward …. 

(switch to announcer voice)
Until Now!
(Ok switch back)

Multiple forward plugins in a single block now are allowed in 1.9.4, which was just released last week.
But for migrating to earlier version than that, we should I guess abort the migration and error that we can’t migrate the config instead of producing a bad one. 

This would pose a problem though, since for multiple version span migrations, we step through each version one at a time, thus when migrating from some ancient version of coredns that still had proxy to 1.9.4 (to be added), it would abort on an intermediate version. Anyways, the use case of migrating from a version that old all the way to 1.9.4 is probably not a situation to fret over.

**Comment by zawachte** [comment]
Makes sense. Going to close this issue as it seems like an extreme corner case not worth maintaining.

The only reason I opened the issue is because I came across a coredns deployment which was failing due to multiple forward entries in the corefile. I was trying to hypothesize what could have got it there, but the more likely case is that someone was just testing some configuration and forgot to clean up.
